# .rubocop.yml
inherit_from: .rubocop_todo.yml

Style/SpaceBeforeFirstArg:
  Enabled: true

Lint/HandleExceptions:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Metrics/AbcSize:
  Max: 15


  
