language: ruby
cache: bundler
rvm:
  - 2.3.1
  - 2.2.5

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database rdolphin_test;' -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:migrate
